# Generated by Django 4.0.3 on 2022-04-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employess',
            new_name='Employees',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployessId',
            new_name='EmployeeId',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployessName',
            new_name='EmployeeName',
        ),
    ]
